coverage:
  precision: 2
  round: up
  range: 75..95
  status:
    project:
      default:
        target: auto
        threshold: 2.5%  # allow for 2.5% reduction of coverage without failing
ignore:
  - "agent/**/*"